services:
  tinylink:
    image: tinylink:dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      Database__Host: postgres
      Database__Port: "5432"
      ForwardedHeaders__KnownNetworks__0: "172.16.0.0/12"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel:4318"
    networks:
      - backend
      - traefik
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=tinylink_traefik"
      - "traefik.http.routers.tinylink.rule=Host(`api.localhost`)"
      - "traefik.http.routers.tinylink.entrypoints=web"
      - "traefik.http.services.tinylink.loadbalancer.server.port=8080"

  postgres:
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5555:5432"
    networks:
      - backend
      - dbaccess
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

  otel:
    image: otel/opentelemetry-collector-contrib:0.159.0
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    networks:
      - traefik

  traefik:
    image: traefik:v3.7
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--tracing.otlp.http.endpoint=http://otel:4318/v1/traces"
      - "--metrics.otlp.http.endpoint=http://otel:4318/v1/metrics"


networks:
  backend:
    internal: true
  traefik:
  dbaccess:

volumes:
  pgdata:

