services:
  tinylink:
    image: tinylink:dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      Database__Host: postgres
      Database__Port: "5432"
    ports:
      - "8080:8080"
    networks:
      - backend
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5555:5432"
    networks:
      - backend
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  pgdata:

